name: foundry-test

on: [push]

env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  TENDERLY_FORK: ${{ secrets.TENDERLY_FORK }}
  RPC_MAINNET: ${{ secrets.RPC_MAINNET }}
  RPC_GNOSIS: ${{ secrets.RPC_GNOSIS }}
  ETHERSCAN_API_KEY_MAINNET: ${{ vars.ETHERSCAN_API_KEY_MAINNET }}
  ETHERSCAN_API_KEY_GNOSIS: ${{ vars.ETHERSCAN_API_KEY_GNOSIS }}
  VERIFIER_URL: ${{ vars.VERIFIER_URL }}

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: npm install
        run: nvm use && npm install

      - name: Install Foundry Dependencies
        run: forge install && forge build

      - name: Run fork test on fork
        run: ./test/foundry/fork-test.sh

      - name: Run end to end test test on fork
        run: ./test/foundry/e2e/e2e-test.sh
